RJ-Cubed/tasty-bytes

- package-lock.json
- server/db/models/user.js
> added new files to models and api

- server/db/models/addresses.js
---
defined the model, no test specs written yet
> address model created

- server/db/models/products.js
> started products model

- server/db/models/reviews.js
---
model defined, no test specs written
> review model created

- server/db/models/categories.js
---
category model creates, no test specs
> categories model created

- server/db/models/orderline.js
> completed orderline model

- server/db/models/review.spec.js
- server/db/models/reviews.js
---
updated per discussion on id PK and added test specs that need to be attempted...
> added the PK id to reviews and added test specs

- server/db/models/index.js
> model index file updated with associations

- server/db/models/order.js
> Order model

- package.json
- script/orderSeed.js
> order line seed working...the whole database is seeded now

- server/api/index.js
- server/api/products.js
- server/db/models/product.js
- server/index.js
> Products routes new

- server/api/users.js
- server/db/models/index.js
- server/index.js
> User routes

- server/api/products.js
> added product reviews route

- server/db/models/product.js
> rounding unit cost to nearest cent

- client/components/index.js
- client/components/orders/order-item.jsx
- client/components/orders/order-view.jsx
- client/index.js
- client/routes.js
- client/store/index.js
- client/store/orders.js
> Admin all orders react#26

- client/components/orders/order-detail.jsx
- client/components/orders/order-item.jsx
- client/routes.js
> cleaned up and refactored much of the order react elements

- client/components/category-card.jsx
- client/components/navbar.js
- client/components/user-card.jsx
- client/routes.js
> admin dropdown on the nav bar

- client/components/navbar.js
- client/components/shoppingCart/shoppingCart.jsx
- client/routes.js
> fixed cart link

- client/components/shoppingCart/cartItem.jsx
- client/components/shoppingCart/shoppingCart.jsx
> a working shopping cart that get info from thunk

- client/components/navbar.js
> logout button now working

- client/store/cartPrice.js
- client/store/index.js
> added cart prices to the store

- client/components/navbar.js
- client/store/cart.js
- client/store/user.js
- server/api/cart.js
> cart now clears on logout

- public/index.html
> added https to stylesheet link

- client/components/products/single-product.jsx
- server/api/products.js
> fixed run time error

- client/components/products/addProduct.jsx
- client/store/products.js
- public/style.css
> new product form validation complete

- client/components/navbar.js
- client/store/shippingInfo.js
> improved navbar

- client/components/navbar.js
- client/components/orders/order-item.jsx
- client/components/orders/order-view.jsx
- client/routes.js
> User orders

- client/components/index.js
- client/components/products/category-selected.jsx
- client/components/products/single-product.jsx
- client/components/reviews/review-card.jsx
- client/routes.js
- server/api/admin/categories.js
- server/api/products.js
- server/auth/index.js
> Categories dropdown

- client/components/products/single-product.jsx
- client/components/user-home.js
- server/api/admin/products.js
- server/api/admin/users.js
- server/api/orders.js
- server/api/reviews.js
- server/api/users.js
> cleaned routes

- client/components/navbar.js
- client/components/products/product-card.jsx
- client/components/products/single-product.jsx
- client/components/reviews/new-review.jsx
- client/components/reviews/review-card.jsx
- server/api/cart.js
> add to cart qty properly incrememnting

- client/components/all-categories.jsx
- client/components/error-message.jsx
- client/components/index.js
- client/components/products/addProduct.jsx
- client/components/products/editProduct.jsx
- client/components/products/single-product.jsx
- client/components/reviews/new-review.jsx
- client/routes.js
- client/store/categories.js
- client/store/index.js
- client/store/pop-up.js
- client/store/products.js
- public/style.css
- server/api/admin/products.js
- server/db/models/category.js
- server/db/models/product.js
- server/index.js
> product, review and category forms all validated

- client/components/navbar.js
- client/components/products/all-products.jsx
- client/components/products/category-selected.jsx
- client/components/products/product-card.jsx
- script/prodSeed.js
> prettified all products page

- client/store/orders.js
- server/api/index.js
- server/api/orders.js
> mdified new order route

- client/components/checkout/orderPrevItem.jsx
- client/components/checkout/orderPreview.jsx
- client/components/orders/order-edit.jsx
- client/components/orders/order-item.jsx
- client/components/orders/order-view.jsx
- client/components/products/editProduct.jsx
- client/components/products/single-product.jsx
- client/store/categories.js
- client/store/orders.js
- client/store/products.js
- client/store/reviews.js
- client/store/shippingInfo.js
> cleaned up files

- client/store/reviews.js
> fix small isse

- client/components/products/product-card.jsx
> refresh bug fixed

- client/components/orders/admin-sort.jsx
- client/components/orders/order-view.jsx
- client/routes.js
- public/style.css
> working urls, probably need more css

- server/db/models/order.js
> deleted useless arrived table

- client/components/shoppingCart/cartItem.jsx
- public/style.css
- server/api/index.js
> minor bug fixes

- client/components/products/all-products.jsx
- client/routes.js
- client/store/categories.js
- server/api/admin/categories.js
- server/api/admin/index.js
- server/api/categories.js
- server/api/index.js
> dropdown working

- client/components/orders/order-view.jsx
- client/routes.js
- client/store/orders.js
> minor fixes

- client/components/checkout/checkout.jsx
- client/components/checkout/confirmation.jsx
- client/components/checkout/orderPreview.jsx
- client/components/shoppingCart/shoppingCart.jsx
> best shipping info i can make

- client/components/products/all-products.jsx
- client/components/products/category-selected.jsx
- client/components/products/product-card.jsx
- client/components/products/single-product.jsx
- script/prodSeed.js
> seeded up products

- client/components/checkout/checkout.jsx
- client/components/reviews/new-review.jsx
- client/store/orders.js
- public/style.css
> Add this branch

- client/components/navbar.js
- client/routes.js
- client/store/orders.js
- public/style.css
- server/api/index.js
> fixed admin access
